version: "3"

services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - .env.dev

  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: luxconsult
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      -
