# Generated by Django 4.2.5 on 2023-09-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Property Title')),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField(default='Description of the property', verbose_name='Description')),
                ('price', models.IntegerField(default=0, verbose_name='Price')),
                ('bedrooms', models.IntegerField(default=0, verbose_name='Number of bedrooms')),
                ('main_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('property_status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], default='For Sale', max_length=20)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
            ],
        ),
    ]
