# Generated by Django 4.2.4 on 2023-10-05 05:14

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property_price_currency_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='KES', max_digits=14),
        ),
    ]
