# Generated by Django 4.2.5 on 2023-10-08 08:09

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_property_video_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=4, verbose_name='Number of bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Description of the property', max_length=30, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default_currency='KES', max_digits=8),
        ),
    ]
