# Generated by Django 4.2.5 on 2023-11-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_property_bedrooms_alter_property_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
        migrations.CreateModel(
            name='VideoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
        ),
    ]
