# Generated by Django 4.2.5 on 2023-12-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_property_photo1_alter_property_photo2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='house_plan',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='VideoTour',
        ),
    ]
